capstone/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('sso/', include("sso.urls")),
    path("", include("livequiz.urls")),
    path("news/", include("news.urls")),
    
    # url routes for password reset purpose
    path("accounts/", include("django.contrib.auth.urls")),
]

livequiz/urls.py
from django.urls import path
from . import views

app_name = "livequiz"
urlpatterns = [
    # Regular URL routes
    path("dashboard", views.index, name="index"),
    path("create", views.createGame, name="create"),
    path("create/<int:game_id>", views.editGame, name="edit"),
    path("host/<int:game_id>", views.hostGame, name="host"),
    path("play/entercode", views.enterGame, name="entercode"),
    path("play/<str:game_code>", views.playGame, name="play"),
    path("result/<str:game_code>", views.result, name="result"),
    
    # API routes
    path("api/retrieve/<str:game_code>", views.retrieveGame),
    path("api/action/<str:game_code>", views.gameAction),
    path("api/savequestion/<str:ques_id>", views.saveQuestion),
]

sso/urls.py
from django.urls import path
from . import views

app_name = "sso"
urlpatterns = [
    path("login", views.loginView, name="login"),
    path("logout", views.logoutView, name="logout"),
    path("register", views.register, name="register"),
    path("comingsoon", views.comingsoonView, name="comingsoon"),
]

livequiz/models.py
from django.db import models
from django.utils.crypto import get_random_string
from sso.models import User


class Game(models.Model):
    id = models.AutoField(primary_key=True)
    creator = models.ForeignKey(User, on_delete=models.CASCADE, related_name="games")
    title = models.CharField(max_length=64, unique=True)
    description = models.CharField(max_length=256)
    date_created = models.DateField(auto_now=True)
    
    def __str__(self):
        return f"<Game {self.id}: {self.title}>"
    
    def question_count(self):
        return QuestionType1.objects.filter(game_origin=self).count()


class GameSession(models.Model):
    id = models.BigAutoField(primary_key=True)
    host = models.ForeignKey(User, on_delete=models.CASCADE, related_name="hosted_games")
    game = models.ForeignKey(Game, on_delete=models.CASCADE, related_name="ongoing", null=True)
    code = models.CharField(max_length=6, primary_key=False, editable=False, unique=True)
    active = models.BooleanField(default=False)
    current_question = models.IntegerField(default=0)
    stillopen = models.BooleanField(default=True)
    finished = models.BooleanField(default=False)
    
    class Meta: verbose_name = "Game Session"
    
    def __str__(self):
        return f"<Gamesession {self.id}, hosted by {self.host}, game id {self.game.id}>"
    
    def save(self, *args, **kwargs):
        if not self.code: self.code = get_random_string(6)
        return super(GameSession, self).save(*args, **kwargs)
    
    def serialize(self):
        return {
            "active": self.active,
            "current_question": self.current_question,
            "stillopen": self.stillopen,
        }
    
    def activate(self, *args, **kwargs):
        self.current_question = 1
        self.active = True
        self.finished = False
        return super(GameSession, self).save(*args, **kwargs)
        
    def deactivate(self, *args, **kwargs):
        self.current_question = 0
        self.active = False
        return super(GameSession, self).save(*args, **kwargs)
        
    def nextquestion(self, *args, **kwargs):
        self.current_question = self.current_question + 1
        self.stillopen = True
        return super(GameSession, self).save(*args, **kwargs)
        
    def closequestion(self, *args, **kwargs):
        self.stillopen = False
        return super(GameSession, self).save(*args, **kwargs)
    
    def status(self):
        if not self.active: return "prep"
        if self.stillopen: return "play"
        elif not self.finished: return "closed"
        else: return "finished"


class QuestionTemplate(models.Model):
    id = models.AutoField(primary_key=True)
    game_origin = models.ForeignKey(Game, on_delete=models.CASCADE, related_name="questions")
    question = models.CharField(max_length=128)
    
    class Meta:
        abstract = True
        order_with_respect_to = "game_origin"
    
    
class QuestionType1(QuestionTemplate):
    choice1 = models.CharField(max_length=64, default="")
    choice2 = models.CharField(max_length=64, default="")
    choice3 = models.CharField(max_length=64, default="", blank=True, null=True)
    choice4 = models.CharField(max_length=64, default="", blank=True, null=True)
    CHOICES = [("1", choice1), ("2", choice2), ("3", choice3), ("4", choice4)]
    answer = models.CharField(max_length=1, choices=CHOICES, default="1")
    
    def serialize(self):
        return {
            "question": self.question,
            "choice1": self.choice1,
            "choice2": self.choice2,
            "choice3": self.choice3,
            "choice4": self.choice4,
        }
        
    def saveedit(self, dict, *args, **kwargs):
        self.question = dict["ques"]
        self.choice1 = dict["opt1"]
        self.choice2 = dict["opt2"]
        self.choice3 = dict["opt3"]
        self.choice4 = dict["opt4"]
        self.answer = dict["ans"]
        return super(QuestionType1, self).save(*args, **kwargs)
        
    def get_answer(self):
        return self.answer #TODO


class UserSession(models.Model):
    player = models.ForeignKey(User, on_delete=models.CASCADE)
    gamesession = models.ForeignKey(GameSession, on_delete=models.CASCADE)
    time_joined = models.DateTimeField(auto_now=True)
    score = models.IntegerField(default=0)
    
    def __str__(self):
        return self.player.username
    
    def updatescore(self, score):
        self.score = score
        return self.save()
    

class AnswerPairType1(models.Model):
    CHOICES = [("0", "unanswered"), ("1", "c1"), ("2", "c2"), ("3", "c3"), ("4", "c4")]
    answer = models.CharField(max_length=1, choices=CHOICES)
    question = models.ForeignKey(QuestionType1, on_delete=models.CASCADE)
    usersession = models.ForeignKey(UserSession, on_delete=models.CASCADE, related_name="answers")
    
    class Meta: verbose_name = "Type 1 Answer Pair"

livequiz/forms.py
from django import forms
from django.utils.safestring import mark_safe


class GameForm(forms.Form):
    title = forms.CharField(label = mark_safe("Title"), max_length = 64,
                            widget = forms.TextInput(attrs = {
                                "class": 'form_title form-control',
                                }))
    description = forms.CharField(widget = forms.Textarea(attrs = {
        'placeholder': "Explain briefly what your game is about...",
        "class": "form_description form-control",
        'rows': 4,
    }), max_length = 256)


class CodeForm(forms.Form):
    sessioncode = forms.CharField(label = "Enter code", max_length = 6,
                                  widget = forms.TextInput(attrs = {
                                      "placeholder": "6-character code",
                                  }))


class AddQuesForm(forms.Form):
    ques_count = forms.IntegerField(label = "Add these amount of questions",
                                    min_value = 1, max_value = 10,
                                    initial = 1)

livequiz/views.py
from django.http import HttpResponse, HttpResponseForbidden, JsonResponse, HttpResponseRedirect, Http404, HttpResponseBadRequest
from django.core import serializers
from django.shortcuts import render
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt
from json import loads

from . import util
from .models import Game, GameSession, QuestionType1, AnswerPairType1, UserSession
from .forms import GameForm, CodeForm, AddQuesForm


@login_required(login_url="sso:login")
def index(request):
    # 'POST' method: delete gamesession (valid as long as gamesession exist & user must be the creator)
    if request.method == "POST":
        session_id = request.POST["session_id"]
        try:
            gamesession = GameSession.objects.get(id = session_id)
        except GameSession.DoesNotExist:
            raise Http404("Gamesession not found!")
        if request.user != gamesession.host:
            return HttpResponse("Unauthorized user!", status = 401)
        gamesession.delete()
    
    # render dashboard page
    return render(request, "livequiz/index.html", {
        "games": Game.objects.all(),
        "gamesessions": GameSession.objects.all(),
        "active": "index",
    })


def createGame(request):
    # 'POST' method: handles form submission of new game creation, redirect to edit page
    if request.method == "POST":
        form = GameForm(request.POST)
        if form.is_valid():
            title = form.cleaned_data["title"]
            description = form.cleaned_data["description"]
            newgame = Game(creator = request.user, title = title, description = description)
            newgame.save()
            return HttpResponseRedirect(reverse("livequiz:edit", kwargs = {
                "game_id": newgame.id,
            }))
        else: return render(request, "livequiz/create.html", {
            "form": form, "active": "create",
        })
        
    # those who have not logged in yet can't fill form nor see their games
    if request.user.is_anonymous:
        return render(request, "livequiz/create.html", { "anonymous": True, "active": "create",})
        
    # 'GET' method: render html with empty form
    return render(request, "livequiz/create.html", {
        "form": GameForm, "active": "create",
        "mygames": Game.objects.filter(creator = request.user),
    })


def editGame(request, game_id):
    # make sure game_id is valid
    try: game = Game.objects.get(id = game_id)
    except KeyError:
        return HttpResponseBadRequest("Bad request: missing game id!")
    except Game.DoesNotExist:
        return HttpResponseBadRequest("Bad Request: invalid game id!")
    
    # dynamic pagination: allow custom no of question per pages, by default 6
    if "qperpage" in request.GET:
        try: num = int(request.GET["qperpage"])
        except TypeError: num = 6
    else: num = 6
    
    # 'POST' method: handles form submission for number of new questions in this game, then refresh page
    if request.method == "POST":
        form = AddQuesForm(request.POST)
        if form.is_valid():
            ques_count = form.cleaned_data["ques_count"]
            for _ in range(int(ques_count)):
                QuestionType1(game_origin = game, answer = 1).save()
            return HttpResponseRedirect(reverse("livequiz:edit", args = (game_id,)))
        else:
            questions = util.getcount(game.questions.all())
            return render(request, "livequiz/edit.html", {
                "game": game, "form": form, "active": "create",
                "questions": util.paginate(request, questions, num).object_list,
                "pagination": util.paginate(request, questions, num),
                "qperpage": num,
            })
            
    # 'GET' method: render edit page with questions and form to add more question
    questions = util.getcount(game.questions.all())
    return render(request, "livequiz/edit.html", {
        "game": game, "form": AddQuesForm, "active": "create",
        "questions": util.paginate(request, questions, num).object_list,
        "pagination": util.paginate(request, questions, num),
        "qperpage": num,
    })


@login_required(login_url="sso:login")
def hostGame(request, game_id):
    # 'POST' method: creates new game session if game_id is an integer and valid, redirect to play page
    if request.method == "POST":
        if game_id not in list(Game.objects.all().values_list('id', flat = True)):
            return Http404("Game ID not found!")
        game_session = GameSession.objects.create(host = request.user,
                                   game = Game.objects.get(id = game_id))
        return HttpResponseRedirect(reverse("livequiz:play", kwargs = {
            "game_code": game_session.code,
        }))
    else:
        return HttpResponseForbidden("This route only supports 'POST' method!")


@login_required(login_url="sso:login")
def enterGame(request):
    # 'POST' method: handles form submission, if valid redirect to play page as participants
    if request.method == "POST":
        form = CodeForm(request.POST)
        valid_codes = GameSession.objects.all().values_list('code', flat = True)
        if form.is_valid() and form.cleaned_data["sessioncode"] in valid_codes:
            return HttpResponseRedirect(reverse("livequiz:play", kwargs = {
                "game_code": form.cleaned_data["sessioncode"],
            }))
        else:
            return render(request, "livequiz/enter.html", {
                "form": form,
                "error": "invalid code!",
                "active": "entercode",
            })
            
    # 'GET' method: renders enter code html page and form
    return render(request, "livequiz/enter.html", { "form": CodeForm, "active": "entercode",})


@login_required(login_url="sso:login")
def playGame(request, game_code):
    # make sure game_code is valid
    try: gamesession = GameSession.objects.get(code=game_code)
    except KeyError:
        return HttpResponseBadRequest("Bad request: missing game session code!")
    except GameSession.DoesNotExist:
        return HttpResponseBadRequest("Bad Request: invalid game session code!")
    
    # create new usersession if there is no existing usersession
    try: 
        UserSession.objects.get(player = request.user, gamesession = gamesession)
    except UserSession.DoesNotExist:
        UserSession.objects.create(player = request.user, gamesession = gamesession)
    
    # render play page (interaction & functionality made through js and api routes)
    gamesession = GameSession.objects.get(code=game_code)
    return render(request, "livequiz/play.html", {
        "game": gamesession.game,
        "gamesession": gamesession,
        "admin": request.user == gamesession.host,
        "total_questions": gamesession.game.question_count(),
        "players": UserSession.objects.filter(gamesession = gamesession), # temporary
        "active": "entercode"
    })
    
    
@login_required(login_url="sso:login")
def result(request, game_code):
    # make sure game_code is valid
    try: gamesession = GameSession.objects.get(code=game_code)
    except KeyError:
        return HttpResponseBadRequest("Bad request: missing game session code!")
    except GameSession.DoesNotExist:
        return HttpResponseBadRequest("Bad Request: invalid game session code!")
    
    # tally all scores
    usersessions = UserSession.objects.filter(gamesession = gamesession)
    for usersession in usersessions:
        score = 0
        answers = AnswerPairType1.objects.filter(usersession = usersession)
        for answer in answers:
            if answer.answer == answer.question.answer:
                score += 1
        usersession.updatescore(score)
        
    print(type(AnswerPairType1.objects.filter(usersession = usersession)))
    print(AnswerPairType1.objects.filter(usersession = usersession)[0])
        
    # render page
    return render(request, "livequiz/result.html", {
        "scores": UserSession.objects.filter(gamesession=gamesession).exclude(player=gamesession.host).order_by("-score"),
        "game": gamesession.game,
    })


@csrf_exempt
def retrieveGame(request, game_code):
    print("RETRIEVE GAME API ROUTE")
    
    # check if gamesession is valid
    try: gamesession = GameSession.objects.get(code = game_code)
    except GameSession.DoesNotExist:
        return JsonResponse({
            "error": "invalid gamesession"
        }, status = 400)

    # return jsonresponse of current question and its options
    if request.method == "VIEW":
        question_ids = gamesession.game.get_questiontype1_order()
        curr_ques_no = gamesession.current_question
        if 1 <= curr_ques_no <= gamesession.game.question_count():
            question = QuestionType1.objects.get(id=question_ids[curr_ques_no - 1])
            return JsonResponse({
                "current_question": question.serialize(),
                "question_no": curr_ques_no,
            })
        else: return JsonResponse({
            "error": "invalid question number"
        }, status = 404)
    
    # return jsonresponse of current game state (started or not)
    elif request.method == "GET":
        print(gamesession.status())
        return JsonResponse({ "status": gamesession.status(),})
    
    # if gamesession is still on 'play' state, register user's answer if not registered yet
    elif request.method == "PUT":
        if gamesession.status() != "play":
            return JsonResponse({ "message": "closed",})
        question_ids = gamesession.game.get_questiontype1_order()
        curr_ques_no = gamesession.current_question
        a = loads(request.body)["answer"]
        q = QuestionType1.objects.get(id=question_ids[curr_ques_no - 1])
        usersession = UserSession.objects.get(player = request.user, gamesession = gamesession)

livequiz/templates/livequiz/create.html
{% extends 'layout/root.html' %}
{% load static %}

{% block title %}
    Create Game
{% endblock title %}

{% block script %}
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    <link href="{% static 'livequiz/create.css' %}" rel="stylesheet">
{% endblock script %}

{% block body %}
    <div class="container">
        <section class="h2 pl-2 pt-2">
            <i class="fa fa-plus-circle fa-fw"></i>
            <span class="p-1">Create</span>
        </section>
        <section class="font-weight-normal">
            Create, view, edit, and host your own games here!
        </section><hr>

        {% if anonymous %}
            <section class="alert alert-danger">
                Please kindly log in to access all these features:<br>
                &bull; Create and edit your own game<br>
                &bull; View your own games and bookmark other games<br>
                &bull; Host a game session with your own / other games<br>
            </section>
        {% else %}
                <div id="accordion">
                    <div class="card">
                        <div class="card-header" id="headingOne">
                            <h4 class="mb-0 h4">
                                <button class="btn btn-link" data-toggle="collapse" data-target="#collapseOne" aria-expanded="false" aria-controls="collapseOne">
                                    <i class="fa fa-plus-square-o" style="font-size:24px">
                                        Create New Game
                                    </i>
                                </button>
                            </h4>
                        </div>
                        <div id="collapseOne" class="collapse" aria-labelledby="headingOne" data-parent="#accordion">
                            <div class="card-body">
                                <form action="{% url 'livequiz:create' %}" method="POST">
                                    {% csrf_token %}
                                    <div class="form-group">
                                        {{ form.title.label_tag }}
                                        {{ form.title }}
                                    </div>
                                    <div class="form-group">
                                        {{ form.description.label_tag }}
                                        {{ form.description }}
                                    </div>
                                    <input type="submit" value="Create" class="btn btn-outline-dark"></input>
                                </form>
                            </div>
                        </div>
                    </div>
                </div><hr>
                
                <div>
                    <section class="h4">
                        <span class="p-1">
                            <u>My Games</u>
                        </span>
                    </section>
        
                    <div class="wrap">
                        {% for game in mygames %}
                            <div class="gamediv">
                                <section class="h5">
                                    <wrap>{{ game.title }}</wrap>
                                </section>
                                <section class="font-weight-normal">
                                    Creator: <b>{{ game.creator.username }}</b>
                                </section>
                                <section class="text-center">
                                    <a href="{% url 'livequiz:edit' game_id=game.id %}">
                                        <button class="btn btn-warning m-2 px-3">
                                            View
                                        </button>
                                    </a>
                                    <form action="{% url 'livequiz:host' game_id=game.id %}" class="inl" method="POST">
                                        {% csrf_token %}
                                        <button type="submit" class="btn btn-info m-2 px-3">
                                            Host
                                        </button>
                                    </form>
                                </section>
                            </div>
                        {% empty %}
                            You have not created any games yet.
                        {% endfor %}
                    </div>
                </div><hr>
        
                <div>
                    Bookmarked games - TODO
                </div>
            </div>
        {% endif %}
{% endblock body %}

livequiz/templates/livequiz/edit.html
{% extends 'layout/root.html' %}
{% load static %}

{% block title %}
    Edit Game
{% endblock title %}

{% block script %}
    <script src="{% static "edit.js" %}" type="module"></script>
    <link href="{% static 'livequiz/edit.css' %}" rel="stylesheet">
{% endblock script %}

{% block body %}
    <div class="container">
        <section class="h3 pl-2 pt-2">
            <span class="p-1"><u>Game Information</u></span>
        </section>
        <table class="h5" style="width: 100%;">
            <colgroup>
                <col span="1" style="width: 30%;">
                <col span="1">
            </colgroup>
            <tr>
                <td>Game Title</td>
                <td>: {{ game.title }}</td>
            </tr>
            <tr>
                <td>Game ID</td>
                <td>: {{ game.id }}</td>
            </tr>
            <tr>
                <td>Date Created</td>
                <td>: {{ game.date_created }}</td>
            </tr>
            <tr>
                <td>Creator</td>
                <td>: {{ game.creator.username }}</td>
            </tr>
        </table><hr>

        {% if request.user != game.creator %}
            <section class="alert alert-warning">
                Note: You can only view the page as you are not the creator!
            </section>
        {% endif %}
        
        {% include 'livequiz/pagination.html' %}
        <section class="text-center">
            <form action="{% url 'livequiz:edit' game_id=game.id %}?qperpage=4" method="GET">
                <label for="qperpage">Question per page: </label>
                <input type="number" min="1" max="20" id="qperpage" value={{ qperpage }} name="qperpage">
                <input type="submit" value="Change">
            </form>
        </section>

        {% for question in questions %}
            <div class="questiondiv" data-quesid={{ question.id }}>
                <h3>Q{{ question.count }}.</h3>
                <section class="questioneditable">
                    <span class="ques_text">Question:</span>
                    <span class="ques">{{ question.question }}</span><br>
                    <span class="opt1_text">Option 1:</span>
                    <span class="opt1">{{ question.choice1 }}</span><br>
                    <span class="opt2_text">Option 2:</span>
                    <span class="opt2">{{ question.choice2 }}</span><br>
                    <span class="opt3_text">Option 3:</span>
                    <span class="opt3">{{ question.choice3 }}</span><br>
                    <span class="opt4_text">Option 4:</span>
                    <span class="opt4">{{ question.choice4 }}</span><br>
                    <span class="ans_text">Ans: </span>
                    <span class="ans">{{ question.answer }}</span><br>
                    {% if request.user == game.creator %}
                        <button class="editbutton" data-quesid={{ question.id }}>
                            Edit
                        </button>
                    {% endif %}
                </section>
                {% if request.user == game.creator %}
                    <button class="deletebutton" value={{ question.id }}>Delete</button>
                {% endif %}
            </div>
        {% empty %}
            No questions created yet!
        {% endfor %}<br>
        
        {% if request.user == game.creator %}
            <form action="{% url 'livequiz:edit' game_id=game.id %}" method="POST">
                {% csrf_token %}
                {{ form.ques_count.label_tag }}
                {{ form.ques_count }}
                <button type="submit">Add</button>
            </form>
        {% endif %}
    </div>
{% endblock body %}

livequiz/templates/livequiz/enter.html
{% extends 'layout/root.html' %}
{% load static %}

{% block title %}
    Enter Code
{% endblock title %}

{% block script %}
    <link href="{% static 'bgcss/bg_entercode.css' %}" rel="stylesheet">
    <link href="{% static 'livequiz/entercode.css' %}" rel="stylesheet">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
{% endblock script %}

{% block body %}
    <div class="container p-3 pb-5">
        <section class="h1 display-1 text-center">
            <span class="glow">
                Enter Code Here
            </span>
        </section>
    </div>

    <form action={% url 'livequiz:entercode' %} method="POST">
        <div class="entercodediv">
            {% csrf_token %}
            <span class="input">
                {{ form.sessioncode }}
                <span></span> 
            </span>
        </div>
        {% if error %}
            <div class="h2 text-center p-2 brightcol">
                {{ error }}
            </div>
        {% endif %}
        <div class="centerdiv pt-3 pb-2 entrance">
            <button class="button" type="submit">
                <span>
                    Play
                </span>
            </button>
        </div>
    </form>

    <div class="centerdiv entrance">
        <a href="{% url 'livequiz:index' %}">
            <button class="button"><span>Home</span></button>
        </a>
    </div>

    <script>
        $(document).ready(() => {
            console.log("ready")
            $(".brightcol").hide(0).slideDown(1000).delay(1000).slideUp(500).slideDown(1500)
            $(".entrance").hide(0).show(1000)
        })
    </script>
{% endblock body %}

livequiz/templates/livequiz/index.html
{% extends 'layout/root.html' %}
{% load static %}

{% block title %}
    Dashboard
{% endblock title %}

{% block script %}
    <link href="{% static 'livequiz/create.css' %}" rel="stylesheet">
    <script src="{% static "index.js" %}" type="module"></script>
{% endblock script %}

{% block body %}
    <div class="container">
        <section class="h2 pl-2 pt-2">
            <i class="fa fa-book fa-fw"></i>
            <span class="p-1">Dashboard</span>
        </section><hr>

        <section class="h3"><u>All Games</u></section>

        <div class="wrap">
            {% for game in games %}
                <div class="gamediv">
                    <section class="h5">
                        <wrap>{{ game.title }}</wrap>
                    </section>
                    <section class="font-weight-normal">
                        Creator: <b>{{ game.creator.username }}</b>
                    </section>
                    <section class="text-center">
                        <a href="{% url 'livequiz:edit' game_id=game.id %}">
                            <button class="btn btn-warning m-2 px-3">
                                View
                            </button>
                        </a>
                        <form action="{% url 'livequiz:host' game_id=game.id %}" class="inl" method="POST">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-info m-2 px-3">
                                Host
                            </button>
                        </form>
                    </section>
                </div>
            {% empty %}
                You have not created any games yet.
            {% endfor %}
        </div><hr>
        
        <section class="h3"><u>All Active Game Sessions</u></section>

        <div class="wrap">
            {% for gamesession in gamesessions %}
                <div class="gamediv heightplus">
                    <section class="font-weight-bold">
                        Game: <b>{{ gamesession.game.title }}</b>
                    </section>
                    <section class="font-weight-normal">
                        Code: <strong>{{ gamesession.code }}</strong>
                    </section>
                    <section class="font-weight-normal">
                        Host: <strong>{{ gamesession.host }}</strong>
                    </section>
                    <section class="text-center">
                        <a href="{% url 'livequiz:play' game_code=gamesession.code %}">
                            <button class="btn btn-success m-2 px-3">
                                Join
                            </button>
                        </a>
                        {% if gamesession.host == request.user %}
                            <form action="{% url 'livequiz:index' %}" method="POST" class="inl">
                                {% csrf_token %}
                                <input type="hidden" name="session_id" value={{ gamesession.id }}>
                                <button type="submit" class="btn btn-danger m-2 px-3">
                                    Delete
                                </button>
                            </form>
                        {% endif %}
                    </section>
                </div>
            {% empty %}
                <section class="h5">
                    No active session available currently.
                </section>
            {% endfor %}
        </div>
    </div>
{% endblock body %}