capstone/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('sso/', include("sso.urls")),
    path("", include("livequiz.urls")),
    path("news/", include("news.urls")),
    
    # url routes for password reset purpose
    path("accounts/", include("django.contrib.auth.urls")),
]

news/urls.py
from django.urls import path
from . import views

app_name = "news"
urlpatterns = [
    path("", views.index, name="index"),
    path("<str:id>", views.renderPage, name="render"),
]

sso/urls.py
from django.urls import path
from . import views

app_name = "sso"
urlpatterns = [
    path("login", views.loginView, name="login"),
    path("logout", views.logoutView, name="logout"),
    path("register", views.register, name="register"),
    path("comingsoon", views.comingsoonView, name="comingsoon"),
]

news/models.py
from django.db import models
from sso.models import User
from markdown2 import markdown


# Create your models here.
class NonStrippingTextField(models.TextField):
    def formfield(self, **kwargs):
        kwargs['strip'] = False
        return super(NonStrippingTextField, self).formfield(**kwargs)


class Information(models.Model):
    id = models.AutoField(primary_key=True)
    creator = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=64)
    description = models.CharField(max_length=128, default="")
    markdown = NonStrippingTextField()
    time_created = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return f"<News ID {self.id}: {self.title}>"
    
    def serialize(self):
        return {
            "id": self.id,
            "creator": self.creator.username,
            "title": self.title,
            "description": self.description,
            "markdown": markdown(self.markdown),
            "time": self.time_created.strftime("%b %d %Y, %I:%M %p"),
        }


class LikePair(models.Model):
    likednews = models.ForeignKey(Information, on_delete=models.CASCADE, related_name="likes")
    liker = models.ForeignKey(User, on_delete=models.CASCADE, related_name="likednewspair")
    

news/views.py
from django.shortcuts import render

from .models import Information


def index(request):
    return render(request, "news/index.html", {
        "infos": Information.objects.all(),
        "admin": (False if request.user.is_anonymous else
                  request.user.status in ["T1", "T2"]),
        "active": "news",
    })


def renderPage(request, id):
    print(Information.objects.get(id = id).serialize())
    return render(request, "news/page.html", {
        "md": Information.objects.get(id = id).serialize(),
        "admin": (False if request.user.is_anonymous else
                  request.user.status in ["T1", "T2"]),
        "active": "news",
    })

news/templates/news/index.html
{% extends 'layout/root.html' %}
{% load static %}

{% block title %}
    All News
{% endblock title %}

{% block script %}
    <link href="{% static 'news/styles.css' %}" rel="stylesheet">
{% endblock script %}

{% block body %}
    <div class="container">
        <section class="h2 pl-2 pt-2">
            <i class="fa fa-newspaper-o fa-fw"></i>
            <span class="p-1">News</span>
        </section>
        <section class="font-weight-normal">
            Find information and latest updates about our website here!
        </section><hr>

        {% if admin %}
            <section class="h5">
                Admin control here (coming soon)
            </section><hr>
        {% endif %}

        {% for info in infos %}
            <div class="news_div">
                {% include 'news/newsdiv.html' %}
            </div>
        {% endfor %}
    </div>
{% endblock body %}

news/templates/news/newsdiv.html
<div>
    <section class="h4">
        <u>{{ info.serialize.title }}</u>
    </section>
    <section class="font-weight-normal text-muted pb-2">
        {{ info.serialize.description }}
    </section>
    <section class="ml-2">
        Written by:
        <span class="font-weight-bold">
            {{ info.serialize.creator }}
        </span>
    </section>
    <section class="ml-2 mb-2">
        Published at:
        <span class="font-weight-normal">
            {{ info.serialize.time }}
        </span>
    </section>
    <section class="ml-2">
        <a href="{% url 'news:render' id=info.serialize.id %}">
            <button class="btn btn-success">Read More</button>
        </a>
    </section>
</div>

news/templates/news/page.html
{% extends 'layout/root.html' %}
{% load static %}

{% block title %}
    News {{ md.id }}
{% endblock title %}

{% block script %}
    <link href="{% static 'news/styles.css' %}" rel="stylesheet">
{% endblock script %}

{% block body %}
    <div class="container">
        <section class="display-4">
            <b>{{ md.title }}</b>
        </section>
        <section class="font-weight-normal">
            Created by: <span><b>{{ md.creator }}</b></span>
        </section>
        <section class="font-weight-normal mb-2">
            Created at: <span>{{ md.time }}</span>
        </section>
        <a href="{% url 'news:index' %}" class="m-2">
            <button class="btn btn-outline-dark">
                Back
            </button>
        </a>
        <hr class="hrmain">

        {% if admin %}
            <section class="h5">
                Admin control here (coming soon)
            </section>
            <hr class="hrmain">
        {% endif %}

        <div class="p-1">
            {{ md.markdown|safe }}
        </div>
    </div>
{% endblock body %}