capstone/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('sso/', include("sso.urls")),
    path("", include("livequiz.urls")),
    path("news/", include("news.urls")),
    
    # url routes for password reset purpose
    path("accounts/", include("django.contrib.auth.urls")),
]

livequiz/urls.py
from django.urls import path
from . import views

app_name = "livequiz"
urlpatterns = [
    # Regular URL routes
    path("dashboard", views.index, name="index"),
    path("create", views.createGame, name="create"),
    path("create/<int:game_id>", views.editGame, name="edit"),
    path("host/<int:game_id>", views.hostGame, name="host"),
    path("play/entercode", views.enterGame, name="entercode"),
    path("play/<str:game_code>", views.playGame, name="play"),
    path("result/<str:game_code>", views.result, name="result"),
    
    # API routes
    path("api/retrieve/<str:game_code>", views.retrieveGame),
    path("api/action/<str:game_code>", views.gameAction),
    path("api/savequestion/<str:ques_id>", views.saveQuestion),
]

news/urls.py
from django.urls import path
from . import views

app_name = "news"
urlpatterns = [
    path("", views.index, name="index"),
    path("<str:id>", views.renderPage, name="render"),
]

sso/urls.py
from django.urls import path
from . import views

app_name = "sso"
urlpatterns = [
    path("login", views.loginView, name="login"),
    path("logout", views.logoutView, name="logout"),
    path("register", views.register, name="register"),
    path("comingsoon", views.comingsoonView, name="comingsoon"),
]

sso/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.
class User(AbstractUser):
    TIER = [
        ("T5", "SuspendedUser"),
        ("T4", "User"),
        ("T3", "StarUser"),
        ("T2", "Admin"),
        ("T1", "SuperAdmin"),
    ]
    status = models.CharField(max_length=2, choices=TIER, default="T4")

sso/views.py
from django.forms import ValidationError
from django.http import HttpResponseRedirect
from django.contrib.auth import login, logout, authenticate
from django.shortcuts import render
from django.urls import reverse
from django.db import IntegrityError
from django.contrib.auth.password_validation import validate_password

from .models import User


def loginView(request):
    # attempt to sign user in and check if authentication successful
    if request.method == "POST":
        user = authenticate(request,
                            username = request.POST["username"],
                            password = request.POST["password"])
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse("livequiz:index"))
        else: return render(request, "sso/login.html", {
            "message": "Invalid username and/or password!"
        })
    else:
        # if user already logged in, redirects to dashboard
        if request.user.is_authenticated:
            return HttpResponseRedirect(reverse("livequiz:index"))
        
        # if not render login form
        return render(request, "sso/login.html")


def logoutView(request):
    # logout the user, display successful logout message
    logout(request)
    return render(request, "sso/logout.html")


def register(request):
    if request.method == "POST":
        username = request.POST["username"]
        email = request.POST["email"]
        
        # username or email cannot be empty
        if not username or not email:
            return render(request, "sso/register.html", {
                "message": "Warning! Please fill all the required fields!",
                "username": username, "email": email,
            })
        
        # ensure password matches confirmation
        password = request.POST["password"]
        confirmation = request.POST["confirmation"]
        if password != confirmation:
            return render(request, "sso/register.html", {
                "message": "Warning! Confirmation password does not match original password!",
                "username": username, "email": email,
            })
            
        # ensure password is not too simple
        try:
            validate_password(password)
        except ValidationError:
            return render(request, "sso/register.html", {
                "message": "Warning! Your password is too simple, pick another password!",
                "username": username, "email": email,
            })
            
        # ensure username is unique (not taken already)
        try:
            user = User.objects.create_user(username, email, password)
            user.save()
        except IntegrityError:
            return render(request, "sso/register.html", {
                "message": "Sorry, username already taken, please pick another username!",
                "username": username, "email": email,
            })
            
        # log user in and redirect to dashboard page
        login(request, user)
        return HttpResponseRedirect(reverse("livequiz:index"))
    else:
        # if user already logged in, redirects to dashboard
        if request.user.is_authenticated:
            return HttpResponseRedirect(reverse("livequiz:index"))
        
        # if not render register form
        else: return render(request, "sso/register.html", {
            "username": "", "email": "",
        })
        

def comingsoonView(request):
    return render(request, "layout/comingsoon.html")

sso/templates/layout/comingsoon.html
{% extends 'layout/root.html' %}
{% load static %}

{% block title %}
    Coming Soon
{% endblock title %}

{% block script %}
    <link href="{% static 'sso/bg_comingsoon.css' %}" rel="stylesheet">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
{% endblock script %}

{% block body %}
    <p class="text-center display-1">
        <b>Coming Soon...</b>
    </p>
    <section class="h4 text-center">
        This feature is currently under construction &#128513
    </section>
    <script>
        // TODO
    </script>
{% endblock body %}

sso/templates/layout/root.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <title>{% block title %}{% endblock title %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="{% static 'sso/layout.css' %}" rel="stylesheet">
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block script %}{% endblock script %}
</head>
<body>
    <div class="container-fluid">
        <div class="row min-vh-100 flex-column flex-md-row">
            <aside class="col-12 col-md-2 p-0 bgsidebar flex-shrink-1">
                <nav class="navbar sticky-top navbar-expand navbar-dark bgsidebar flex-md-column flex-row align-items-start py-2">
                    <div class="collapse navbar-collapse col-fixed">
                        {% include 'layout/sidebar.html' %}
                    </div>
                </nav>
            </aside>
            <main class="col bg-faded py-3 flex-grow-1">
                <div class="body">
                    {% block body %}{% endblock body %}
                </div>
            </main>
        </div>
    </div>
</body>
</html>

sso/templates/layout/sidebar.html
{% load static %}
<script src="{% static "sso/sso.js" %}" type="module"></script>

<ul class="flex-md-column flex-row navbar-nav w-100 justify-content-between">
    <div id="capstonetitle">
        <li class="nav-item m-1 hide">
            <span class="capstonetitle">Capstone</span>
        </li>
    </div>
    <li class="nav-item ml-2">
        <span class="font-weight-bold mt-4">
            <a href="{% url 'sso:comingsoon' %}" class="nav-link pl-0">
                <i class="fa fa-user fa-fw"></i>
                <span class="d-none d-md-inline">
                    {% if user.is_authenticated %}
                        <strong class="h4">{{ user.username }}</strong>
                    {% else %}
                        Not logged in.
                    {% endif %}
                </span>
            </a>
        </span>
    </li>
    {% if user.is_authenticated %}
        <li class="nav-item ml-2">
            <a class="nav-link pl-0" href="{% url 'sso:logout' %}">
                <i class="fa fa-sign-out fa-fw"></i>
                <span class="d-none d-md-inline h5">Logout</span>
            </a>
        </li>
    {% else %}
        <li class="nav-item ml-2">
            <a class="nav-link pl-0" href="{% url 'sso:login' %}">
                <i class="fa fa-sign-in fa-fw"></i>
                <span class="d-none d-md-inline h5">Login</span>
            </a>
        </li>
        <li class="nav-item ml-2">
            <a class="nav-link pl-0" href="{% url 'sso:register' %}">
                <i class="fa fa-external-link-square fa-fw"></i>
                <span class="d-none d-md-inline h5">Register</span>
            </a>
        </li>
    {% endif %}

    {% if active == "index" %}
        <li class="nav-item ml-2 active">
            <a class="nav-link pl-0" href="{% url 'livequiz:index' %}">
                <i class="fa fa-book fa-fw"></i>
                <span class="d-none d-md-inline h5">Dashboard</span>
            </a>
        </li>
    {% else %}
        <li class="nav-item ml-2">
            <a class="nav-link pl-0" href="{% url 'livequiz:index' %}">
                <i class="fa fa-book fa-fw"></i>
                <span class="d-none d-md-inline h5">Dashboard</span>
            </a>
        </li>
    {% endif %}
    
    {% if active == "entercode" %}
        <li class="nav-item ml-2 active">
            <a class="nav-link pl-0" href="{% url 'livequiz:entercode' %}">
                <i class="fa fa-star fa-fw"></i>
                <span class="d-none d-md-inline h5">Enter Code</span>
            </a>
        </li>
    {% else %}
        <li class="nav-item ml-2">
            <a class="nav-link pl-0" href="{% url 'livequiz:entercode' %}">
                <i class="fa fa-star fa-fw"></i>
                <span class="d-none d-md-inline h5">Enter Code</span>
            </a>
        </li>
    {% endif %}

    {% if active == "create" %}
        <li class="nav-item ml-2 active">
            <a class="nav-link pl-0" href="{% url 'livequiz:create' %}">
                <i class="fa fa-plus-circle fa-fw"></i>
                <span class="d-none d-md-inline h5">Create</span>
            </a>
        </li>
    {% else %}
        <li class="nav-item ml-2">
            <a class="nav-link pl-0" href="{% url 'livequiz:create' %}">
                <i class="fa fa-plus-circle fa-fw"></i>
                <span class="d-none d-md-inline h5">Create</span>
            </a>
        </li>
    {% endif %}
    
    {% if active == "news" %}
        <li class="nav-item ml-2 active">
            <a class="nav-link pl-0" href="{% url 'news:index' %}">
                <i class="fa fa-newspaper-o fa-fw"></i>
                <span class="d-none d-md-inline h5">News</span>
            </a>
        </li>
    {% else %}
        <li class="nav-item ml-2">
            <a class="nav-link pl-0" href="{% url 'news:index' %}">
                <i class="fa fa-newspaper-o fa-fw"></i>
                <span class="d-none d-md-inline h5">News</span>
            </a>
        </li>
    {% endif %}

    <li class="nav-item ml-2">
        <a class="nav-link pl-0" href="{% url 'sso:comingsoon' %}">
            <i class="fa fa-heart codeply fa-fw text-muted"></i>
            <span class="d-none d-md-inline h5 text-muted">Community</span>
        </a>
    </li>
    <li class="nav-item ml-2">
        <a class="nav-link pl-0" href="{% url 'sso:comingsoon' %}">
            <i class="fa fa-question-circle fa-fw text-muted"></i>
            <span class="d-none d-md-inline h5 text-muted">Guide</span>
        </a>
    </li>

    <li class="nav-item ml-2 d-none d-md-inline btm-pos">
        <div class="nav-link pl-0" href="https://github.com/michac789">
            <a class="colwh" href="https://github.com/michac789">
                <i class="fa fa-github fa-fw" style="font-size:36px"></i>
            </a>
            <a class="colwh" href="https://sg.linkedin.com/in/michael-andrew-chan-144a29219">
                <i class="fa fa-linkedin-square fa-fw" style="font-size:36px"></i>
            </a>
        </div>
        <div class="colwh p-1">
            <p>&copy; michac789</p>
        </div>
    </li>
</ul>